#!/bin/bash

# http://www.ostricher.com/2014/10/the-right-way-to-get-the-directory-of-a-bash-script/

get_script_dir () {
     SOURCE="${BASH_SOURCE[0]}"
     while [ -h "$SOURCE" ]; do
          DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          SOURCE="$( readlink "$SOURCE" )"
          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
     done
     $( cd -P "$( dirname "$SOURCE" )" )
     pwd
}

THIS_DIR=$(get_script_dir)
THIS_NAME="web3"

. "$THIS_DIR/config"

docker stop "${THIS_NAME}-MysqlDB"
docker rm "${THIS_NAME}-MysqlDB"
docker stop "${THIS_NAME}-PhpApache"
docker rm "${THIS_NAME}-PhpApache"
docker stop "${THIS_NAME}-PhpMyAdmin"
docker rm "${THIS_NAME}-PhpMyAdmin"


docker run -d --name "${THIS_NAME}-MysqlDB" -p 3306:3306 -v "${THIS_DIR}/db":/var/lib/mysql \
       -e "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" \
       -e "MYSQL_USER=${MYSQL_USER}" \
       -e "MYSQL_PASSWORD=${MYSQL_PASSWORD}" \
       -e "MYSQL_DATABASE=${MYSQL_DATABASE}" mysql

MYSQL_DB_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${THIS_NAME}-MysqlDB)

docker run -d --name "${THIS_NAME}-PhpApache" \
       --link "${THIS_NAME}-MysqlDB:mysql" \
       -p 8080:80 \
       -p 8443:443 \
       -v "${THIS_DIR}":/var/www/html \
       php:apache

docker exec "${THIS_NAME}-PhpApache" docker-php-ext-install pdo pdo_mysql
docker exec "${THIS_NAME}-PhpApache" a2enmod ssl
docker cp certs/apache-selfsigned.crt web3-PhpApache:/etc/ssl/certs/apache-selfsigned.crt
docker cp certs/apache-selfsigned.key web3-PhpApache:/etc/ssl/private/apache-selfsigned.key
docker cp apache2/sites-available/default-ssl.conf web3-PhpApache:/etc/apache2/sites-available/default-ssl.conf
docker exec "${THIS_NAME}-PhpApache" a2ensite default-ssl
docker restart "${THIS_NAME}-PhpApache"

docker run -d --name "${THIS_NAME}-PhpMyAdmin" \
       --link "${THIS_NAME}-MysqlDB:db" \
       -e "PMA_USER=root" \
       -e "PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}" \
       -p 8888:80 \
       phpmyadmin/phpmyadmin

PHP_MY_ADMIN_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${THIS_NAME}-PhpMyAdmin)
